[package]
name = "rwutil"
version = "1.0.0"
authors = ["Marc Brinkmann <git@marcbrinkmann.de>"]
license = "MIT"
description = "Extends io::{Read,Write} with methods for reading length-prefixed strings"
repository = "https://github.com/mbr/rwutil-rs"

[dependencies]
byteorder = "^0.4"
